### ISSUE TITLE
License

### ISSUE THREAD

**Issue by spotlesscoder** [awesomebytes/ubuntu14_dell_xps13_9350#4]
Hi,

could you please add a LICENSE file to the repo?

Thank you :)

**Comment by awesomebytes** [comment]
It's just a set of instructions, I don't believe it needs any license. In
case you need it, as the author, I consider this Creative Commons.

**Comment by spotlesscoder** [comment]
It's always better to have a license, at least in Germany ;)

**Comment by awesomebytes** [comment]
I consider this like a blog post. It contains no code files, just instructions, so there isn't much IP there anyways.
I'll just close this issue.
